// Generated by CoffeeScript 1.7.1
var config, tools;

tools = require('../tools');

config = require('../config');

exports.index = function(req, res) {
  return res.render('index', {
    title: 'Express'
  });
};
